deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  etcd:
    host:
      - "http://etcd:2379"
    prefix: /apisix
    timeout: 30
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9092
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
    allow_admin:
      - 0.0.0.0/0

apisix:
  id: apisix-poc-node-1
  node_listen: 9080
  enable_ipv6: false

plugin_attr:
  opa:
    host: "http://opa:8181"
    timeout: 3000

plugins:
  - openid-connect
  - opa
  - proxy-rewrite
  - response-rewrite
  - cors
  - limit-req
  - request-id
  - serverless-pre-function
